<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

    <Import Project="CommonTests.props"/>

    <PropertyGroup>
        <IsTestProject>true</IsTestProject>
        <TestSdkVersion>17.13.0</TestSdkVersion>
        <VisualStudioRunnerVersion>3.0.2</VisualStudioRunnerVersion>
        <CoverletColectorVersion>6.0.4</CoverletColectorVersion>
    </PropertyGroup>
    <PropertyGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">
        <TestSdkVersion>18.9.0</TestSdkVersion>
        <VisualStudioRunnerVersion>4.0.0</VisualStudioRunnerVersion>
        <CoverletColectorVersion>10.0.1</CoverletColectorVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Xunit.SkippableFact" Version="1.5.85"/>
        <PackageReference Include="xunit" Version="2.9.3"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="$(TestSdkVersion)"/>
        <PackageReference Include="xunit.runner.visualstudio" Version="$(VisualStudioRunnerVersion)">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector" Version="$(CoverletColectorVersion)">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>
