using System;
using System.Runtime.CompilerServices;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

// ReSharper disable UseRawString

namespace Rxmxnx.JNetInterface.SourceGenerator;

internal static partial class GenerationExtensions
{
	private const String ObjectRefFormat = @"#nullable enable
// <auto-generated/>
namespace {0};

partial struct {1}
{{
	/// <inheritdoc/>
	public Boolean IsDefault => this == default({1});{2}
}}
#nullable restore";

	private const String ObjectRefOverrideFormat = @"
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public override Int32 GetHashCode() => this._value.GetHashCode();
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public override Boolean Equals([NotNullWhen(true)] Object? obj) => {0}(this, obj);
";

	/// <summary>
	/// Generates operators for object reference structures.
	/// </summary>
	/// <param name="objRefSymbol">A type symbol of object reference structure.</param>
	/// <param name="context">Generation context.</param>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static void GenerateObjectRefOperators(this ISymbol objRefSymbol, SourceProductionContext context)
	{
		String fileName = $"{objRefSymbol.Name}.ObjRef.g.cs";
		String equalFunction = objRefSymbol.Name.Contains("ArrayLocalRef") ?
			"JArrayLocalRef.ArrayEquals" :
			"JObjectLocalRef.ObjectEquals";
		String overrides = objRefSymbol.Name == "JArrayLocalRef" ?
			String.Empty :
			String.Format(GenerationExtensions.ObjectRefOverrideFormat, equalFunction);
		String source = String.Format(GenerationExtensions.ObjectRefFormat, objRefSymbol.ContainingNamespace,
		                              objRefSymbol.Name, overrides);
#pragma warning disable RS1035
		context.AddSource(fileName, SourceText.From(source, Encoding.UTF8));
#pragma warning restore RS1035
	}
}