using System;
using System.Runtime.CompilerServices;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

// ReSharper disable UseRawString

namespace Rxmxnx.JNetInterface.SourceGenerator;

internal static partial class GenerationExtensions
{
	private const String NumericPrimitiveOperatorsFormat = @"#nullable enable
// <auto-generated/>
namespace {0};

partial struct {1} : ISpanFormattable, IMinMaxValue<{1}>, IBinaryNumber<{1}>, INumericValue<{1}>
{{
	/// <inheritdoc cref=""IMinMaxValue{{TSelf}}.MinValue""/>
	public static readonly {1} MinValue = {2}.MinValue;
	/// <inheritdoc cref=""IMinMaxValue{{TSelf}}.MaxValue""/>
	public static readonly {1} MaxValue = {2}.MaxValue;
{3}

	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Boolean INumberBase<{1}>.IsZero({1} value) => value._value == 0;
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Boolean INumberBase<{1}>.IsCanonical({1} value) => true;
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Boolean INumberBase<{1}>.IsComplexNumber({1} value) => false;
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Boolean INumberBase<{1}>.IsImaginaryNumber({1} value) => false;
{4}

    /// <inheritdoc cref=""IComparisonOperators{{TSelf, TOther, Boolean}}.op_GreaterThan(TSelf, TOther)"" />
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Boolean operator >({1} left, {1} right) => left.CompareTo(right) > 0;
	/// <inheritdoc cref=""IComparisonOperators{{TSelf, TOther, Boolean}}.op_GreaterThanOrEqual(TSelf, TOther)"" />
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Boolean operator >=({1} left, {1} right) => left.CompareTo(right) >= 0;
    /// <inheritdoc cref=""IComparisonOperators{{TSelf, TOther, Boolean}}.op_LessThanOrEqual(TSelf, TOther)"" />
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Boolean operator <=({1} left, {1} right) => left.CompareTo(right) <= 0;
    /// <inheritdoc cref=""IComparisonOperators{{TSelf, TOther, Boolean}}.op_LessThan(TSelf, TOther)"" />
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Boolean operator <({1} left, {1} right) => left.CompareTo(right) < 0;

	/// <inheritdoc cref=""IModulusOperators{{TSelf, TOther, TResult}}.op_Modulus(TSelf, TOther)"" />
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static {1} operator %({1} left, {1} right) 
		=> NumericHelper.Modulus(left.{5}, right.{5});

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static {1} operator --({1} value) => NumericHelper.Decrement(value.{5});
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static {1} operator checked --({1} value) => NumericHelper.CheckedDecrement(value.{5});
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static {1} operator ++({1} value) => NumericHelper.Increment(value.{5});
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static {1} operator checked ++({1} value) => NumericHelper.CheckedIncrement(value.{5});

	static {1} IMinMaxValue<{1}>.MinValue => {1}.MinValue;
	static {1} IMinMaxValue<{1}>.MaxValue => {1}.MaxValue;
	static Int32 INumberBase<{1}>.Radix => 2;
}}
#nullable restore";

	private const String NumericFormattableFormat = @"
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public String ToString(String? format, IFormatProvider? formatProvider) => this.Value.ToString(format, formatProvider);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public Boolean TryFormat(Span<Char> destination, out Int32 charsWritten, ReadOnlySpan<Char> format = default, IFormatProvider? provider = default)
		=> this.Value.TryFormat(destination, out charsWritten, format, provider);
#if NET8_0_OR_GREATER
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public Boolean TryFormat(Span<Byte> destination, out Int32 bytesWritten, ReadOnlySpan<Char> format = default, IFormatProvider? provider = default)
		=> this.Value.TryFormat(destination, out bytesWritten, format, provider);
#endif

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static {0} Abs({0} value) => {1}.Abs(value._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Boolean IsEvenInteger({0} value) => {1}.IsEvenInteger(value._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Boolean IsOddInteger({0} value) => {1}.IsOddInteger(value._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Boolean IsNegative({0} value) => {1}.IsNegative(value._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Boolean IsPositive({0} value) => {1}.IsPositive(value._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static {0} MaxMagnitude({0} x, {0} y) => {1}.MaxMagnitude(x._value, y._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static {0} MinMagnitude({0} x, {0} y) => {1}.MinMagnitude(x._value, y._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static {0} Parse(String s, IFormatProvider? provider)
	    => {1}.Parse(s, provider);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static {0} Parse(String s, NumberStyles style, IFormatProvider? provider)
	    => {1}.Parse(s, style, provider);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static {0} Parse(ReadOnlySpan<Char> s, IFormatProvider? provider)
	    => {1}.Parse(s, provider);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static {0} Parse(ReadOnlySpan<Char> s, NumberStyles style, IFormatProvider? provider)
	    => {1}.Parse(s, style, provider);
#if NET8_0_OR_GREATER
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static {0} Parse(ReadOnlySpan<Byte> s, IFormatProvider? provider)
	    => {1}.Parse(s, provider);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static {0} Parse(ReadOnlySpan<Byte> s, NumberStyles style, IFormatProvider? provider)
	    => {1}.Parse(s, style, provider);
#endif
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Boolean TryParse([NotNullWhen(true)] String? s, IFormatProvider? provider,
		out {0} result)
	{{
		Unsafe.SkipInit(out result);
		return {1}.TryParse(s, provider, out Unsafe.As<{0}, {1}>(ref result));
	}}
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Boolean TryParse([NotNullWhen(true)] String? s, NumberStyles style, IFormatProvider? provider,
		out {0} result)
	{{
		Unsafe.SkipInit(out result);
		return {1}.TryParse(s, style, provider, out Unsafe.As<{0}, {1}>(ref result));
	}}
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Boolean TryParse(ReadOnlySpan<Char> s, IFormatProvider? provider, out {0} result)
	{{
		Unsafe.SkipInit(out result);
		return {1}.TryParse(s, provider, out Unsafe.As<{0}, {1}>(ref result));
	}}
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Boolean TryParse(ReadOnlySpan<Char> s, NumberStyles style, IFormatProvider? provider, out {0} result)
	{{
		Unsafe.SkipInit(out result);
		return {1}.TryParse(s, style, provider, out Unsafe.As<{0}, {1}>(ref result));
	}}
#if NET8_0_OR_GREATER
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Boolean TryParse(ReadOnlySpan<Byte> s, IFormatProvider? provider, out {0} result)
	{{
		Unsafe.SkipInit(out result);
		return {1}.TryParse(s, provider, out Unsafe.As<{0}, {1}>(ref result));
	}}
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Boolean TryParse(ReadOnlySpan<Byte> s, NumberStyles style, IFormatProvider? provider, out {0} result)
	{{
		Unsafe.SkipInit(out result);
		return {1}.TryParse(s, style, provider, out Unsafe.As<{0}, {1}>(ref result));
	}}
#endif
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Boolean IsPow2({0} value) => NumericHelper.IsPow2(value.Value);
	/// <inheritdoc cref=""IBinaryNumber{{TSelf}}.Log2(TSelf)""/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static {0} Log2({0} value) => NumericHelper.Log2(value.Value);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static {0} operator +({0} left, {0} right) 
		=> NumericHelper.Addition(left._value, right._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static {0} operator checked +({0} left, {0} right) 
		=> NumericHelper.CheckedAddition(left._value, right._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static {0} operator /({0} left, {0} right)
		=> NumericHelper.Division(left._value, right._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static {0} operator checked /({0} left, {0} right)
		=> NumericHelper.CheckedDivision(left._value, right._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static {0} operator *({0} left, {0} right)
		=> NumericHelper.Multiply(left._value, right._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static {0} operator checked *({0} left, {0} right)
		=> NumericHelper.CheckedMultiply(left._value, right._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static {0} operator -({0} left, {0} right)
		=> NumericHelper.Subtraction(left._value, right._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static {0} operator checked -({0} left, {0} right)
		=> NumericHelper.CheckedSubtraction(left._value, right._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static {0} operator +({0} value)
		=> NumericHelper.UnaryPlus(value._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static {0} operator -({0} value)
		=> NumericHelper.UnaryNegation(value._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static {0} operator checked -({0} value)
		=> NumericHelper.CheckedUnaryNegation(value._value);";

	private const String CharFormattable = @"
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	String IFormattable.ToString(String? format, IFormatProvider? formatProvider) 
		=> NumericHelper.ToString(this.Value, format, formatProvider);
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	Boolean ISpanFormattable.TryFormat(Span<Char> destination, out Int32 charsWritten, ReadOnlySpan<Char> format, IFormatProvider? provider)
		=> NumericHelper.TryFormat(this.Value, destination, out charsWritten, format, provider);
#if NET8_0_OR_GREATER
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	Boolean IUtf8SpanFormattable.TryFormat(Span<Byte> destination, out Int32 bytesWritten, ReadOnlySpan<Char> format, IFormatProvider? provider)
		=> NumericHelper.TryFormat(this.Value, destination, out bytesWritten, format, provider);
#endif

	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Boolean IBinaryNumber<JChar>.IsPow2(JChar value) => NumericHelper.IsPow2(value.Value);
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static JChar IBinaryNumber<JChar>.Log2(JChar value) => NumericHelper.Log2(value.Value);

	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static JChar INumberBase<JChar>.Abs(JChar value) => value;
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Boolean INumberBase<JChar>.IsEvenInteger(JChar value) => (value._value & 1) == 0;
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Boolean INumberBase<JChar>.IsOddInteger(JChar value) => (value._value & 1) != 0;
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Boolean INumberBase<JChar>.IsNegative(JChar value) => false;
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Boolean INumberBase<JChar>.IsPositive(JChar value) => true;
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static JChar INumberBase<JChar>.MaxMagnitude(JChar x, JChar y) => (Char)Math.Max(x._value, y._value);
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static JChar INumberBase<JChar>.MinMagnitude(JChar x, JChar y) => (Char)Math.Min(x._value, y._value);
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static JChar INumberBase<JChar>.Parse(String s, NumberStyles style, IFormatProvider? provider)
	    => NumericHelper.Parse<Char>(s, style, provider);
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static JChar INumberBase<JChar>.Parse(ReadOnlySpan<Char> s, NumberStyles style, IFormatProvider? provider)
	    => NumericHelper.Parse<Char>(s, style, provider);
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Boolean INumberBase<JChar>.TryParse(String? s, NumberStyles style, IFormatProvider? provider,
		out JChar result)
	{{
		Unsafe.SkipInit(out result);
		return NumericHelper.TryParse<Char>(s, style, provider, out Unsafe.As<JChar, Char>(ref result));
	}}
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Boolean INumberBase<JChar>.TryParse(ReadOnlySpan<Char> s, NumberStyles style, IFormatProvider? provider,
		out JChar result)
	{{
		Unsafe.SkipInit(out result);
		return NumericHelper.TryParse<Char>(s, style, provider, out Unsafe.As<JChar, Char>(ref result));
	}}

	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static JChar IAdditionOperators<JChar, JChar, JChar>.operator +(JChar left, JChar right) 
		=> (Char)NumericHelper.Addition(left._value, right._value);
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static JChar IAdditionOperators<JChar, JChar, JChar>.operator checked +(JChar left, JChar right) 
		=> (Char)NumericHelper.CheckedAddition(left._value, right._value);

	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static JChar IDivisionOperators<JChar, JChar, JChar>.operator /(JChar left, JChar right)
		=> (Char)NumericHelper.Division(left._value, right._value);
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static JChar IDivisionOperators<JChar, JChar, JChar>.operator checked /(JChar left, JChar right)
		=> (Char)NumericHelper.CheckedDivision(left._value, right._value);

	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static JChar IMultiplyOperators<JChar, JChar, JChar>.operator *(JChar left, JChar right)
		=> (Char)NumericHelper.Multiply(left._value, right._value);
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static JChar IMultiplyOperators<JChar, JChar, JChar>.operator checked *(JChar left, JChar right)
		=> (Char)NumericHelper.CheckedMultiply(left._value, right._value);

	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static JChar ISubtractionOperators<JChar, JChar, JChar>.operator -(JChar left, JChar right)
		=> (Char)NumericHelper.Subtraction(left._value, right._value);
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static JChar ISubtractionOperators<JChar, JChar, JChar>.operator checked -(JChar left, JChar right)
		=> (Char)NumericHelper.CheckedSubtraction(left._value, right._value);

	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static JChar IUnaryPlusOperators<JChar, JChar>.operator +(JChar value)
		=> (Char)NumericHelper.UnaryPlus(value._value);

	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static JChar IUnaryNegationOperators<JChar, JChar>.operator -(JChar value)
		=> (Char)NumericHelper.UnaryNegation(value._value);
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static JChar IUnaryNegationOperators<JChar, JChar>.operator checked -(JChar value)
		=> (Char)NumericHelper.CheckedUnaryNegation(value._value);

	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static JChar IParsable<JChar>.Parse(String s, IFormatProvider? provider)
	    => NumericHelper.Parse<Char>(s, provider);
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Boolean IParsable<JChar>.TryParse(String? s, IFormatProvider? provider, out JChar result)
	{{
		Unsafe.SkipInit(out result);
		return NumericHelper.TryParse<Char>(s, provider, out Unsafe.As<JChar, Char>(ref result));
	}}

	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static JChar ISpanParsable<JChar>.Parse(ReadOnlySpan<Char> s, IFormatProvider? provider)
	    => NumericHelper.Parse<Char>(s, provider);
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Boolean ISpanParsable<JChar>.TryParse(ReadOnlySpan<Char> s, IFormatProvider? provider, out JChar result)
	{{
		Unsafe.SkipInit(out result);
		return NumericHelper.TryParse<Char>(s, provider, out Unsafe.As<JChar, Char>(ref result));
	}}
#if NET8_0_OR_GREATER
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static JChar IUtf8SpanParsable<JChar>.Parse(ReadOnlySpan<Byte> s, IFormatProvider? provider)
	    => NumericHelper.Parse<Char>(s, provider);
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Boolean IUtf8SpanParsable<JChar>.TryParse(ReadOnlySpan<Byte> s, IFormatProvider? provider, out JChar result)
	{{
		Unsafe.SkipInit(out result);
		return NumericHelper.TryParse<Char>(s, provider, out Unsafe.As<JChar, Char>(ref result));
	}}
#endif";

	private const String IntegerFormattableFormat = @"
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Boolean INumberBase<{0}>.IsFinite({0} value) => true;
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Boolean INumberBase<{0}>.IsInfinity({0} value) => false;
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Boolean INumberBase<{0}>.IsInteger({0} value) => true;
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Boolean INumberBase<{0}>.IsNaN({0} value) => false;
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Boolean INumberBase<{0}>.IsNegativeInfinity({0} value) => false;
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Boolean INumberBase<{0}>.IsNormal({0} value) => (value._value != 0);
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Boolean INumberBase<{0}>.IsPositiveInfinity({0} value) => false;
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Boolean INumberBase<{0}>.IsRealNumber({0} value) => true;
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Boolean INumberBase<{0}>.IsSubnormal({0} value) => false;
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static {0} INumberBase<{0}>.MaxMagnitudeNumber({0} x, {0} y) 
		=> NumericHelper.MaxMagnitudeNumber(x.{1}, y.{1});
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static {0} INumberBase<{0}>.MinMagnitudeNumber({0} x, {0} y) 
		=> NumericHelper.MinMagnitudeNumber(x.{1}, y.{1});

	/// <inheritdoc cref=""IBitwiseOperators{{TSelf, TOther, TResult}}.op_BitwiseAnd(TSelf, TOther)"" />
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static {0} operator &({0} left, {0} right) 
		=> NumericHelper.BitwiseAnd(left.{1}, right.{1});
	/// <inheritdoc cref=""IBitwiseOperators{{TSelf, TOther, TResult}}.op_BitwiseOr(TSelf, TOther)"" />
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static {0} operator |({0} left, {0} right) 
		=> NumericHelper.BitwiseOr(left.{1}, right.{1});
	/// <inheritdoc cref=""IBitwiseOperators{{TSelf, TOther, TResult}}.op_ExclusiveOr(TSelf, TOther)"" />
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static {0} operator ^({0} left, {0} right) 
		=> NumericHelper.ExclusiveOr(left.{1}, right.{1});
	/// <inheritdoc cref=""IBitwiseOperators{{TSelf, TOther, TResult}}.op_OnesComplement(TSelf)"" />
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static {0} operator ~({0} value) => NumericHelper.OnesComplement(value.{1});";

	private const String FloatingFormattableFormat = @"
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Boolean IsFinite({0} value) => {1}.IsFinite(value._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Boolean IsInfinity({0} value) => {1}.IsInfinity(value._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Boolean IsInteger({0} value) => {1}.IsInteger(value._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Boolean IsNaN({0} value) => {1}.IsNaN(value._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Boolean IsNegativeInfinity({0} value) => {1}.IsNegativeInfinity(value._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Boolean IsNormal({0} value) => {1}.IsNormal(value._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Boolean IsPositiveInfinity({0} value) => {1}.IsPositiveInfinity(value.Value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Boolean IsRealNumber({0} value) => {1}.IsRealNumber(value._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Boolean IsSubnormal({0} value) => {1}.IsSubnormal(value._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static {0} MaxMagnitudeNumber({0} x, {0} y) => {1}.MaxMagnitudeNumber(x._value, y._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static {0} MinMagnitudeNumber({0} x, {0} y) => {1}.MinMagnitudeNumber(x._value, y._value);

	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static {0} IBitwiseOperators<{0}, {0}, {0}>.operator &({0} left, {0} right) 
		=> NumericHelper.BitwiseAnd(left._value, right._value);
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static {0} IBitwiseOperators<{0}, {0}, {0}>.operator |({0} left, {0} right) 
		=> NumericHelper.BitwiseOr(left._value, right._value);
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static {0} IBitwiseOperators<{0}, {0}, {0}>.operator ^({0} left, {0} right) 
		=> NumericHelper.ExclusiveOr(left._value, right._value);
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static {0} IBitwiseOperators<{0}, {0}, {0}>.operator ~({0} value) 
		=> NumericHelper.OnesComplement(value._value);";

	private const String SignedNumberConstantsFormat = @"#nullable enable
// <auto-generated/>
namespace {0};

partial struct {1} : ISignedNumber<{1}>
{{
	/// <inheritdoc cref=""ISignedNumber{{{1}}}.NegativeOne""/>
	internal static readonly {1} NegativeOne = NumericHelper.NegativeOne<{2}>();

	static {1} ISignedNumber<{1}>.NegativeOne => {1}.NegativeOne;
}};";

	private const String NumberConstantsFormat = @"#nullable enable
// <auto-generated/>
namespace {0};

partial struct {1}
{{
	/// <inheritdoc cref=""IBinaryNumber{{{1}}}.AllBitsSet""/>
	private static readonly {1} allBitsSet = NumericHelper.AllBitsSet<{2}>();
	/// <inheritdoc cref=""IAdditiveIdentity{{{1}, {1}}}.AdditiveIdentity""/>
	private static readonly {1} additiveIdentity = NumericHelper.AdditiveIdentity<{2}>();
	/// <inheritdoc cref=""IMultiplicativeIdentity{{{1}, {1}}}.MultiplicativeIdentity""/>
	private static readonly {1} multiplicativeIdentity = NumericHelper.MultiplicativeIdentity<{2}>();

	/// <inheritdoc cref=""INumberBase{{{1}}}.One""/>
	internal static readonly {1} One = NumericHelper.One<{2}>();
	/// <inheritdoc cref=""INumberBase{{{1}}}.Zero""/>
	internal static readonly {1} Zero = NumericHelper.Zero<{2}>();

	static {1} INumberBase<{1}>.One => {1}.One;
	static {1} INumberBase<{1}>.Zero => {1}.Zero;
	static {1} IBinaryNumber<{1}>.AllBitsSet => {1}.allBitsSet;
	static {1} IAdditiveIdentity<{1}, {1}>.AdditiveIdentity => {1}.additiveIdentity;
	static {1} IMultiplicativeIdentity<{1}, {1}>.MultiplicativeIdentity => {1}.multiplicativeIdentity;
}};";

	/// <summary>
	/// Generates operators for numeric structures.
	/// </summary>
	/// <param name="numericSymbol">A type symbol of numeric structure.</param>
	/// <param name="context">Generation context.</param>
	/// <param name="underlineType">Primitive underline type.</param>
	/// <param name="valueName">Internal absolute value field name.</param>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static void GeneratePrimitiveNumericOperators(this ISymbol numericSymbol, SourceProductionContext context,
		String underlineType, String valueName)
	{
		String fileName = $"{numericSymbol.Name}.Numeric.g.cs";
		String formattable = numericSymbol.Name is "JChar" ?
			GenerationExtensions.CharFormattable :
			String.Format(GenerationExtensions.NumericFormattableFormat, numericSymbol.Name, underlineType);
		String numerics = numericSymbol.Name is "JDouble" or "JFloat" ?
			String.Format(GenerationExtensions.FloatingFormattableFormat, numericSymbol.Name, underlineType) :
			String.Format(GenerationExtensions.IntegerFormattableFormat, numericSymbol.Name, valueName);
		String source = String.Format(GenerationExtensions.NumericPrimitiveOperatorsFormat,
		                              numericSymbol.ContainingNamespace, numericSymbol.Name, underlineType, formattable,
		                              numerics, valueName);
#pragma warning disable RS1035
		context.AddSource(fileName, SourceText.From(source, Encoding.UTF8));
		fileName = $"{numericSymbol.Name}.NumberConstants.g.cs";
		source = String.Format(GenerationExtensions.NumberConstantsFormat, numericSymbol.ContainingNamespace,
		                       numericSymbol.Name, underlineType);
		context.AddSource(fileName, SourceText.From(source, Encoding.UTF8));

		if (numericSymbol.Name is "JChar") return;

		fileName = $"{numericSymbol.Name}.NegativeOne.g.cs";
		source = String.Format(GenerationExtensions.SignedNumberConstantsFormat, numericSymbol.ContainingNamespace,
		                       numericSymbol.Name, underlineType);
		context.AddSource(fileName, SourceText.From(source, Encoding.UTF8));
#pragma warning restore RS1035
	}
}