using System;
using System.Runtime.CompilerServices;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

// ReSharper disable UseRawString

namespace Rxmxnx.JNetInterface.SourceGenerator;

internal static partial class GenerationExtensions
{
	private const String ArrayRefFormat = @"#nullable enable
// <auto-generated/>
namespace {0};

partial struct {1} : IWrapper<JArrayLocalRef>
{{
	[ExcludeFromCodeCoverage]
	JArrayLocalRef IWrapper<JArrayLocalRef>.Value => this.ArrayValue;
}}
#nullable restore";

	/// <summary>
	/// Generates operators for array reference structures.
	/// </summary>
	/// <param name="arrayRefSymbol">A type symbol of array reference structure.</param>
	/// <param name="context">Generation context.</param>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static void GenerateArrayRefOperators(this ISymbol arrayRefSymbol, SourceProductionContext context)
	{
		String fileName = $"{arrayRefSymbol.Name}.ArrayRef.g.cs";
		String source = String.Format(GenerationExtensions.ArrayRefFormat, arrayRefSymbol.ContainingNamespace,
		                              arrayRefSymbol.Name);
#pragma warning disable RS1035
		context.AddSource(fileName, SourceText.From(source, Encoding.UTF8));
#pragma warning restore RS1035
	}
}