name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
permissions:
  actions: write
  contents: write
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_USE_MSBUILD_SERVER: false
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            7.0.x
            8.0.x
            9.0.x
            10.0.x
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Cache SonarCloud packages
        uses: actions/cache@v5
        with:
          path: ~/sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v5
        with:
          path: ./.sonar/scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          New-Item -Path ./.sonar/scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner

      - name: Remove ApplicationTest
        shell: bash
        run: |
          find src/ApplicationTest -name "*.*proj" -exec dotnet sln src remove {} \;
          mv src/ApplicationTest ./ApplicationTest

      - name: Clean test results
        run: rm -rf TestResults/

      - name: Build and analyze Sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: pwsh
        run: |
          ./.sonar/scanner/dotnet-sonarscanner begin /k:"josephmoresena_Rxmxnx.JNetInterface" /o:"josephmoresena" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.scanner.scanAll=false /d:sonar.coverage.exclusions="**Test.cs,**Tests.cs,**test.cs,**tests.cs,**/SourceGenerator/**/*.cs,**/ApplicationTest/**/*,**/Test/**/*.cs,**/Localization/**MessageResource.cs" /d:sonar.cpd.exclusions="**Test.cs,**Tests.cs,**test.cs,**tests.cs,**/SourceGenerator/**/*.cs,**/ApplicationTest/**/*,**/Test/**/*.cs,**/Localization/**MessageResource.cs" /d:sonar.cs.vstest.reportsPaths=TestResults/*.trx /d:sonar.cs.opencover.reportsPaths=TestResults/*/coverage.opencover.xml 
          dotnet build-server shutdown
          dotnet restore src --ignore-failed-sources
          dotnet restore src/Test/Proxies/Native/JvmProxy.NativeProxy.slnx
          dotnet build src /p:MultipleFrameworkTest=true --no-restore --configuration Release --disable-build-servers /nr:false /maxcpucount:1
          dotnet test src /p:MultipleFrameworkTest=true --no-build --no-restore --configuration release --verbosity normal --collect:"XPlat Code Coverage" --results-directory TestResults/ --logger "trx;verbosity=detailed" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
          ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
      - name: Pack core assembly
        working-directory: ./package/Rxmxnx.JNetInterface.Core
        run: |
          dotnet pack -c Release -o ../Nuget /p:Version=9999.99.99.99-tmp /p:NoIntermediateBuild=true
          for package in ../Nuget/Rxmxnx.JNetInterface.Core*.*nupkg; do
            echo "-----------------------------------"
            TEMP_DIR=$(mktemp -d)
            unzip -q "$package" -d "$TEMP_DIR"
            ls -sh "$package"
            tree "$TEMP_DIR" -h --noreport | tail -n +2 | sed "s|$TEMP_DIR/||"
            rm -rf "$TEMP_DIR"
          done
          echo "-----------------------------------"
      - name: Pack main assembly
        working-directory: ./package/Rxmxnx.JNetInterface
        run: |
          dotnet pack -c Release /p:Version=9999.99.99.99-tmp /p:NoIntermediateBuild=true
          for package in bin/Release/Rxmxnx.JNetInterface*.*nupkg; do
            echo "-----------------------------------"
            TEMP_DIR=$(mktemp -d)
            unzip -q "$package" -d "$TEMP_DIR"
            ls -sh "$package"
            tree "$TEMP_DIR" -h --noreport | tail -n +2 | sed "s|$TEMP_DIR/||"
            rm -rf "$TEMP_DIR"
          done
          echo "-----------------------------------"
          mv bin/Release/*.*nupkg ../Nuget

      - name: Cache NuGet Packages
        uses: actions/cache/save@v5
        with:
          path: ./package/Nuget
          key: internal-nuget-${{ github.run_id }}
          enableCrossOsArchive: true
      - name: Cache Compiled Tests
        uses: actions/cache/save@v5
        with:
          path: |
            ./src/Test/**/bin/Release/net9.0
          key: internal-tests-bin-${{ github.run_id }}
  
  android-actions:
    needs: [ build ]
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/android-actions.yml
    secrets: inherit
  freebsd-actions:
    needs: [ build ]
    uses: ./.github/workflows/freebsd-actions.yml
    with:
      run_tests: true
      build_artifacts: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
  freebsd-arm64-actions:
    needs: [ build ]
    uses: ./.github/workflows/freebsd-arm64-actions.yml
    with:
      run_tests: true
      build_artifacts: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
  cross-actions:
    needs: [ build ]
    uses: ./.github/workflows/cross-actions.yml
    with:
      run_tests: true
      build_artifacts: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
  
  cleanup-cache:
    name: Secure Cleanup
    needs: [ build, android-actions, freebsd-actions, cross-actions ]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Java FreeBSD Libraries
        uses: actions/cache/restore@v5
        if: needs.freebsd-actions.result == 'success' && needs.cross-actions.result == 'success'
        with:
          path: ./artifacts-java
          key: internal-freebsd-${{ github.run_id }}
          fail-on-cache-miss: true
          enableCrossOsArchive: true
      - name: Java FreeBSD arm64 Libraries
        uses: actions/cache/restore@v5
        if: needs.freebsd-arm64-actions.result == 'success' && needs.cross-actions.result == 'success'
        with:
          path: ./artifacts-java
          key: internal-freebsd-${{ github.run_id }}
          fail-on-cache-miss: true
          enableCrossOsArchive: true
      - name: Java MacOS Libraries
        uses: actions/cache/restore@v5
        if: needs.cross-actions.result == 'success'
        with:
          path: ./artifacts-java
          key: internal-macOS-${{ github.run_id }}
          fail-on-cache-miss: true
          enableCrossOsArchive: true
      - name: Java Linux Libraries
        uses: actions/cache/restore@v5
        if: needs.cross-actions.result == 'success'
        with:
          path: ./artifacts-java
          key: internal-Linux-${{ github.run_id }}
          fail-on-cache-miss: true
          enableCrossOsArchive: true
      - name: Java Windows Libraries
        uses: actions/cache/restore@v5
        if: needs.cross-actions.result == 'success'
        with:
          path: ./artifacts-java
          key: internal-Windows-${{ github.run_id }}
          fail-on-cache-miss: true
          enableCrossOsArchive: true
      - name: Create Java Artifact
        if: needs.freebsd-actions.result == 'success' || needs.cross-actions.result == 'success'
        uses: actions/upload-artifact@v6
        with:
          name: Java-Artifact
          path: |
            ./artifacts-java/*
      - name: Delete Internal Cache
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          echo "Deleting caches..."
          gh cache delete "internal-nuget-${{ github.run_id }}" || true
          gh cache delete "internal-freebsd-${{ github.run_id }}" || true
          gh cache delete "internal-freebsd-arm64-${{ github.run_id }}" || true
          gh cache delete "internal-Windows-${{ github.run_id }}" || true
          gh cache delete "internal-Linux-${{ github.run_id }}" || true
          gh cache delete "internal-macOS-${{ github.run_id }}" || true
          gh cache delete "internal-tests-${{ github.run_id }}" || true