name: Release to Nuget

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      SNK_BASE64: ${{ secrets.SN_KEY }}
      PUBLIC_KEY: ${{ secrets.SN_PK }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
    - name: Compile intermediate
      working-directory: ./src/Intermediate
      run: |
          dotnet build -c Release ./Rxmxnx.JNetInterface.Base.Intermediate
          dotnet build -c Release ./Rxmxnx.JNetInterface.Primitives.Intermediate
          dotnet build -c Release ./Rxmxnx.JNetInterface.Native.Intermediate
          dotnet build -c Release ./Rxmxnx.JNetInterface.Extensions.Intermediate
          dotnet build -c Release ./Rxmxnx.JNetInterface.Implementation.Intermediate
    - name: Patch ILLink.LinkAttributes
      working-directory: ./src/Intermediate/Rxmxnx.JNetInterface.Base.Intermediate/ILLink
      run: sed -i -z 's/Rxmxnx.JNetInterface.Base.Intermediate/Rxmxnx.JNetInterface.Core/g;' ILLink.LinkAttributes.xml
    - name: Patch ILLink.Substitutions
      working-directory: ./src/Intermediate/Rxmxnx.JNetInterface.Native.Intermediate/ILLink
      run: sed -i -z 's/Rxmxnx.JNetInterface.Native.Intermediate/Rxmxnx.JNetInterface.Core/g;' ILLink.Substitutions.xml
    - name: Extract public key
      working-directory: ./package
      run: echo "${SNK_BASE64}" | base64 -d > Rxmxnx.JNetInterface.snk
    - name: Create Core NuGet Package
      working-directory: ./package/Rxmxnx.JNetInterface.Core
      run: dotnet pack -c Release -o ../Nuget /p:Version=${{ github.event.release.tag_name }} /p:PackageReleaseNotes="See https://github.com/josephmoresena/Rxmxnx.JNetInterface/releases/tag/${{ github.event.release.tag_name }}"
    - name: Create NuGet Package
      working-directory: ./package/Rxmxnx.JNetInterface
      run: dotnet pack -c Release -o ../Nuget /p:Version=${{ github.event.release.tag_name }} /p:PackageReleaseNotes="See https://github.com/josephmoresena/Rxmxnx.JNetInterface/releases/tag/${{ github.event.release.tag_name }}"
    - name: Push NuGet Package
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json
